Check in all changes made so far toward 3.0.

diff --git a/acprep b/acprep
--- a/acprep
+++ b/acprep
@@ -17,31 +17,71 @@ else
 fi
 autoconf
 
-INCDIRS="-I/sw/include -I/sw/include/boost -I/usr/include/httpd/xml"
-#INCDIRS="$INCDIRS -I/sw/include/libofx"
-INCDIRS="$INCDIRS -I/usr/include/python2.3"
-INCDIRS="$INCDIRS -Wno-long-double"
-LIBDIRS="-L/sw/lib -L/usr/local/lib -L/usr/lib/python2.3/config"
+INCDIRS="-I/usr/local/include"
+INCDIRS="$INCDIRS -I/usr/local/include/boost"
+INCDIRS="$INCDIRS -I/usr/include/httpd/xml"
+INCDIRS="$INCDIRS -I/Library/Frameworks/Python.framework/Versions/2.5/include/python2.5"
+
+LIBDIRS="-L/usr/local/lib"
+LIBDIRS="$LIBDIRS -L/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5"
+
+SYSTEM=`uname -s`
+if [ $SYSTEM = Linux ]; then
+    CXXFLAGS="-pthread"
+elif [ $SYSTEM = Solaris ]; then
+    CXXFLAGS="-pthreads"
+elif [ $SYSTEM = Darwin ]; then
+    CXXFLAGS="-Wno-long-double"
+else
+    CXXFLAGS=""
+fi
+
+# Building the command-line tool as a shared library is a luxury,
+# since there are no clients except a GUI tool which might use it (and
+# that is built again anyway by Xcode).
+SWITCHES="--disable-shared"
+
+HERE="$PWD"
+
+#if [ -d "$HOME/Products" ]; then
+#    projdir="$HOME/Products/$(basename $HERE)"
+#    if [ ! -d "$projdir" ]; then
+#	mkdir -p "$projdir"
+#    fi
+#    cd "$projdir" || (echo "Cannot change to $projdir"; exit 1)
+#fi
 
 if [ "$1" = "--debug" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" \
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" $SWITCHES \
+	--enable-debug "$@"
+elif [ "$1" = "--python-debug" ]; then
+    shift 1
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" $SWITCHES \
 	--enable-debug --enable-python "$@"
 elif [ "$1" = "--opt" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
-	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450 -fPIC" "$@"
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450 -fPIC" "$@" $SWITCHES
 elif [ "$1" = "--flat-opt" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
-	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450" "$@"
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450" "$@" $SWITCHES
 elif [ "$1" = "--safe-opt" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
-	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450 -fPIC -DDEBUG_LEVEL=1" "$@"
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450 -fPIC -DDEBUG_LEVEL=1" "$@" \
+	$SWITCHES
 elif [ "$1" = "--perf" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g -pg" "$@"
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g -pg" "$@" \
+	$SWITCHES
 fi
 
 rm AUTHORS COPYING
