Updated the build process in acprep and configure.in to run without issues, and to work with the Buildbot.

diff --git a/acprep b/acprep
--- a/acprep
+++ b/acprep
@@ -1,47 +1,60 @@
 #!/bin/sh
 
+export AUTOCONF_VERSION=2.61
+export AUTOMAKE_VERSION=1.9
+
 touch AUTHORS COPYING
 
-if which glibtoolize > /dev/null 2>&1; then
-    glibtoolize --automake -f -c
-else
-    libtoolize --automake -f -c
+cmd=$(which glibtoolize 2>&1)
+if [ -x "$cmd" ]; then
+    export LIBTOOLIZE="$cmd"
 fi
-aclocal
-autoheader
-if [ "$1" = "--dist" ]; then
-    shift 1
-    automake -a -c -f -i
-else
-    automake -a -c -f
-fi
-autoconf
+autoreconf --force --install
 
-INCDIRS="-I/sw/include -I/sw/include/boost -I/usr/include/httpd/xml"
-#INCDIRS="$INCDIRS -I/sw/include/libofx"
-INCDIRS="$INCDIRS -I/usr/include/python2.3"
+HERE="$PWD"
+
+if [ ! "$1" = "--local" ]; then
+    if [ -d "$HOME/Products" ]; then
+	projdir="$HOME/Products/$(basename $HERE)"
+	if [ ! -d "$projdir" ]; then
+	    mkdir -p "$projdir"
+	fi
+	cd "$projdir" || (echo "Cannot change to $projdir"; exit 1)
+    fi
+else
+    shift 1
+fi
+
+INCDIRS="-I/opt/local/include -I/usr/local/include -I/usr/include/httpd/xml"
+INCDIRS="$INCDIRS -I/usr/include/python2.5"
 INCDIRS="$INCDIRS -Wno-long-double"
-LIBDIRS="-L/sw/lib -L/usr/local/lib -L/usr/lib/python2.3/config"
+LIBDIRS="-L/opt/local/lib -L/usr/local/lib"
 
 if [ "$1" = "--debug" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" \
+    $HERE/configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" \
 	--enable-debug --enable-python "$@"
 elif [ "$1" = "--opt" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+    $HERE/configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
 	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450 -fPIC" "$@"
 elif [ "$1" = "--flat-opt" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+    $HERE/configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
 	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450" "$@"
 elif [ "$1" = "--safe-opt" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+    $HERE/configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
 	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450 -fPIC -DDEBUG_LEVEL=1" "$@"
 elif [ "$1" = "--perf" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g -pg" "$@"
+    $HERE/configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g -pg" "$@"
+elif [ "$1" = "--python" ]; then
+    shift 1
+    $HERE/configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" \
+	--enable-python "$@"
+else
+    $HERE/configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" "$@"
 fi
 
-rm AUTHORS COPYING
+rm -f AUTHORS COPYING
